import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';

// Curated courses from various platforms including FREE courses
function getCuratedCourses(query: string, category: string) {
  const allCourses = [
    // FREE Computer Science / BCA courses from multiple platforms
    {
      name: 'CS50: Introduction to Computer Science',
      category: 'Computer Science',
      duration: '100 hours',
      level: 'Beginner',
      description: 'Harvard\'s introduction to computer science and programming. Learn C, Python, SQL, HTML, CSS, JavaScript and more.',
      platform: 'edX (FREE)',
      url: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
      instructor: 'Harvard University',
      rating: 4.9,
      students: '4M+',
    },
    {
      name: 'Introduction to Computer Science',
      category: 'Computer Science',
      duration: '40 hours',
      level: 'Beginner',
      description: 'Learn programming fundamentals, algorithms, and problem-solving with Python. Completely FREE.',
      platform: 'Saylor Academy (FREE)',
      url: 'https://learn.saylor.org/course/view.php?id=6',
      instructor: 'Saylor Academy',
      rating: 4.7,
      students: '500K+',
    },
    {
      name: 'Programming in Python',
      category: 'Programming',
      duration: '30 hours',
      level: 'Beginner',
      description: 'Master Python programming from scratch with hands-on projects. FREE certification available.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/python-programming',
      instructor: 'Great Learning',
      rating: 4.8,
      students: '800K+',
    },
    {
      name: 'Python for Everybody',
      category: 'Programming',
      duration: '60 hours',
      level: 'Beginner',
      description: 'Learn Python programming fundamentals, data structures, databases, and web scraping. Completely FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/specializations/python',
      instructor: 'University of Michigan',
      rating: 4.8,
      students: '2.5M+',
    },
    {
      name: 'Full Stack Web Development',
      category: 'Web Development',
      duration: '80 hours',
      level: 'Intermediate',
      description: 'Learn HTML, CSS, JavaScript, React, Node.js, MongoDB. Build full-stack applications from scratch.',
      platform: 'freeCodeCamp (FREE)',
      url: 'https://www.freecodecamp.org/learn',
      instructor: 'freeCodeCamp',
      rating: 4.8,
      students: '5M+',
    },
    {
      name: 'Java Programming Basics',
      category: 'Programming',
      duration: '35 hours',
      level: 'Beginner',
      description: 'Learn Java fundamentals, OOP concepts, and build real-world applications. FREE course.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/java-programming',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '600K+',
    },
    {
      name: 'Complete Web Development Bootcamp',
      category: 'Web Development',
      duration: '65 hours',
      level: 'Beginner',
      description: 'Learn HTML, CSS, JavaScript, Node, React, MongoDB, and more! Build 16+ projects and become a full-stack developer.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
      instructor: 'Dr. Angela Yu',
      rating: 4.7,
      students: '380,000+',
    },
    {
      name: 'Machine Learning by Stanford',
      category: 'Machine Learning',
      duration: '60 hours',
      level: 'Intermediate',
      description: 'Learn machine learning algorithms, neural networks, and AI. Taught by Andrew Ng. FREE course.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/machine-learning',
      instructor: 'Andrew Ng',
      rating: 4.9,
      students: '4.8M+',
    },
    {
      name: 'Introduction to Artificial Intelligence',
      category: 'AI',
      duration: '25 hours',
      level: 'Beginner',
      description: 'Learn AI basics, machine learning fundamentals, and neural networks. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/introduction-to-artificial-intelligence',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '400K+',
    },
    {
      name: 'Data Structures and Algorithms',
      category: 'Programming',
      duration: '50 hours',
      level: 'Intermediate',
      description: 'Master data structures and algorithms with visualizations, problem-solving, and coding practice.',
      platform: 'YouTube (FREE)',
      url: 'https://www.youtube.com/watch?v=8hly31xKli0',
      instructor: 'freeCodeCamp',
      rating: 4.9,
      students: '2M+',
    },
    {
      name: 'Cloud Computing Fundamentals',
      category: 'Cloud Computing',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn cloud basics, AWS, Azure fundamentals. FREE with certification.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/cloud-computing',
      instructor: 'Great Learning',
      rating: 4.6,
      students: '350K+',
    },
    {
      name: 'Python for Data Science and Machine Learning',
      category: 'Data Science',
      duration: '25 hours',
      level: 'Intermediate',
      description: 'Learn Python for data analysis, visualization, and machine learning with NumPy, Pandas, Seaborn, Matplotlib, Scikit-Learn, and TensorFlow.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
      instructor: 'Jose Portilla',
      rating: 4.6,
      students: '520,000+',
    },
    {
      name: 'React - The Complete Guide',
      category: 'Web Development',
      duration: '48 hours',
      level: 'Beginner',
      description: 'Master React with Hooks, Redux, React Router, Next.js, and build amazing projects from scratch.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
      instructor: 'Maximilian Schwarzmüller',
      rating: 4.6,
      students: '540,000+',
    },
    {
      name: 'Introduction to Cloud Computing',
      category: 'Cloud Computing',
      duration: '12 hours',
      level: 'Beginner',
      description: 'Learn cloud computing basics, AWS, Azure, Google Cloud. FREE certification available.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/introduction-to-cloud',
      instructor: 'IBM',
      rating: 4.7,
      students: '500K+',
    },
    {
      name: 'Cyber Security Basics',
      category: 'Cyber Security',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Learn cybersecurity fundamentals, network security, ethical hacking basics. FREE course.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/cyber-security',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '450K+',
    },
    {
      name: 'Java Programming Masterclass',
      category: 'Programming',
      duration: '80 hours',
      level: 'Beginner',
      description: 'Learn Java from zero to hero. Master object-oriented programming, data structures, and build real applications.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/java-the-complete-java-developer-course/',
      instructor: 'Tim Buchalka',
      rating: 4.5,
      students: '670,000+',
    },
    {
      name: 'AWS Certified Solutions Architect',
      category: 'Cloud Computing',
      duration: '26 hours',
      level: 'Intermediate',
      description: 'Pass the AWS Certified Solutions Architect Associate exam and become an AWS expert with hands-on practice.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/',
      instructor: 'Stephane Maarek',
      rating: 4.7,
      students: '790,000+',
    },
    {
      name: 'Introduction to Programming',
      category: 'Programming',
      duration: '30 hours',
      level: 'Beginner',
      description: 'Start your programming journey with fundamentals of coding. FREE course from Saylor.',
      platform: 'Saylor Academy (FREE)',
      url: 'https://learn.saylor.org/course/view.php?id=73',
      instructor: 'Saylor Academy',
      rating: 4.6,
      students: '300K+',
    },
    
    // FREE Business / BCom courses from multiple platforms
    {
      name: 'Financial Accounting Basics',
      category: 'Accounting',
      duration: '25 hours',
      level: 'Beginner',
      description: 'Learn accounting fundamentals, financial statements, journal entries. FREE from Coursera.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/wharton-accounting',
      instructor: 'University of Pennsylvania',
      rating: 4.7,
      students: '450K+',
    },
    {
      name: 'Accounting Fundamentals',
      category: 'Accounting',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Master basic accounting principles, bookkeeping, and financial reporting. Completely FREE.',
      platform: 'Shiksha Online (FREE)',
      url: 'https://www.shiksha.com/online-courses/accounting-courses',
      instructor: 'Shiksha',
      rating: 4.6,
      students: '250K+',
    },
    {
      name: 'Introduction to Finance',
      category: 'Finance',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn finance basics, time value of money, valuation, and financial analysis. Completely FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/finance',
      instructor: 'University of Michigan',
      rating: 4.8,
      students: '600K+',
    },
    {
      name: 'Financial Management Basics',
      category: 'Finance',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn financial planning, budgeting, and investment basics. FREE certification.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/financial-management',
      instructor: 'Great Learning',
      rating: 4.6,
      students: '300K+',
    },
    {
      name: 'GST and Taxation in India',
      category: 'Taxation',
      duration: '12 hours',
      level: 'Beginner',
      description: 'Complete guide to GST, income tax filing, and tax compliance. FREE from Great Learning.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/gst-and-taxation',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '200K+',
    },
    {
      name: 'Financial Accounting Fundamentals',
      category: 'Accounting',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Master accounting basics, financial statements, journal entries, and prepare for professional certifications.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/accounting-financial-accounting-bookkeeping-for-beginners/',
      instructor: 'Chris Benjamin',
      rating: 4.5,
      students: '110,000+',
    },
    {
      name: 'Excel Skills for Business',
      category: 'Business',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Master Excel from basics to advanced: formulas, pivot tables, macros, data analysis, and financial modeling.',
      platform: 'Coursera',
      url: 'https://www.coursera.org/specializations/excel',
      instructor: 'Macquarie University',
      rating: 4.8,
      students: '290,000+',
    },
    {
      name: 'Excel Basics for Data Analysis',
      category: 'Business',
      duration: '10 hours',
      level: 'Beginner',
      description: 'Learn Excel formulas, pivot tables, charts, and data analysis. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/excel-for-beginners',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '400K+',
    },
    {
      name: 'Introduction to Taxation in India',
      category: 'Taxation',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn Indian tax system, GST basics, income tax filing. FREE course for beginners.',
      platform: 'YouTube (FREE)',
      url: 'https://www.youtube.com/watch?v=7XDB7tBncas',
      instructor: 'CA Rachana Ranade',
      rating: 4.8,
      students: '1M+',
    },
    {
      name: 'Complete GST & Taxation Course',
      category: 'Taxation',
      duration: '12 hours',
      level: 'Intermediate',
      description: 'Master Indian GST, income tax, TDS, and tax compliance for business and professionals.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/complete-gst-course/',
      instructor: 'CA Yash Khandelwal',
      rating: 4.5,
      students: '85,000+',
    },
    {
      name: 'Tally ERP 9 Complete Training',
      category: 'Accounting Software',
      duration: '10 hours',
      level: 'Beginner',
      description: 'Complete Tally ERP 9 course for accounting, inventory management, GST, and financial reporting.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/tally-erp9/',
      instructor: 'ExpertRating',
      rating: 4.4,
      students: '120,000+',
    },
    {
      name: 'Introduction to Business Management',
      category: 'Business',
      duration: '25 hours',
      level: 'Beginner',
      description: 'Learn business fundamentals, management principles, and organizational behavior. FREE.',
      platform: 'Saylor Academy (FREE)',
      url: 'https://learn.saylor.org/course/view.php?id=82',
      instructor: 'Saylor Academy',
      rating: 4.6,
      students: '350K+',
    },
    {
      name: 'Corporate Finance Fundamentals',
      category: 'Finance',
      duration: '18 hours',
      level: 'Intermediate',
      description: 'Learn corporate finance, financial analysis, valuation, and capital budgeting. FREE on Coursera.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/corporate-finance',
      instructor: 'IESE Business School',
      rating: 4.7,
      students: '300K+',
    },
    {
      name: 'Corporate Finance & Financial Modeling',
      category: 'Finance',
      duration: '28 hours',
      level: 'Advanced',
      description: 'Build financial models in Excel, perform valuation analysis, and create investment portfolios like Wall Street pros.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/financial-analysis-and-financial-modeling-using-ms-excel/',
      instructor: '365 Careers',
      rating: 4.6,
      students: '85,000+',
    },
    
    // FREE BDA - Business Data Analytics courses from multiple platforms
    {
      name: 'Data Analysis with Python (IBM)',
      category: 'Data Analytics',
      duration: '25 hours',
      level: 'Beginner',
      description: 'Learn Python for data analysis with Pandas, NumPy, and visualization. FREE on Coursera.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/data-analysis-with-python',
      instructor: 'IBM',
      rating: 4.7,
      students: '850K+',
    },
    {
      name: 'Data Science Fundamentals',
      category: 'Data Science',
      duration: '30 hours',
      level: 'Beginner',
      description: 'Learn data science basics, Python, statistics, and machine learning. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/data-science-foundations',
      instructor: 'Great Learning',
      rating: 4.8,
      students: '500K+',
    },
    {
      name: 'Introduction to Data Analytics',
      category: 'Data Analytics',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn data analytics basics, tools, and techniques. Perfect for BDA students. FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/introduction-to-data-analytics',
      instructor: 'IBM',
      rating: 4.8,
      students: '400K+',
    },
    {
      name: 'Statistics for Data Science',
      category: 'Statistics',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Master statistical concepts for data analysis. FREE with certificate.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/statistics-for-data-science',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '350K+',
    },
    {
      name: 'Business Analytics Foundations',
      category: 'Business Analytics',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Learn business analytics, data-driven decision making, and insights. Completely FREE.',
      platform: 'Shiksha Online (FREE)',
      url: 'https://www.shiksha.com/online-courses/business-analytics-courses',
      instructor: 'Shiksha',
      rating: 4.6,
      students: '200K+',
    },
    {
      name: 'Business Intelligence and Data Analytics',
      category: 'Business Analytics',
      duration: '32 hours',
      level: 'Intermediate',
      description: 'Master Power BI, Tableau, and SQL for business intelligence, data visualization, and analytics.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/business-intelligence-analyst-course/',
      instructor: '365 Careers',
      rating: 4.5,
      students: '120,000+',
    },
    {
      name: 'SQL for Data Science',
      category: 'Database',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn SQL from scratch for data analysis, queries, and database management. FREE course.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/sql-for-data-science',
      instructor: 'University of California',
      rating: 4.6,
      students: '550K+',
    },
    {
      name: 'SQL Basics for Beginners',
      category: 'Database',
      duration: '12 hours',
      level: 'Beginner',
      description: 'Master SQL fundamentals, queries, joins, and database operations. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/sql-for-beginners',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '450K+',
    },
    {
      name: 'Data Analysis with Python',
      category: 'Data Analytics',
      duration: '22 hours',
      level: 'Intermediate',
      description: 'Master Python for data analysis with Pandas, NumPy, Matplotlib, and statistical analysis.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/data-analysis-with-pandas/',
      instructor: 'Boris Paskhaver',
      rating: 4.6,
      students: '180,000+',
    },
    {
      name: 'Microsoft Power BI Desktop for Business Intelligence',
      category: 'Business Intelligence',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Master Power BI for data visualization, DAX, and creating professional business intelligence reports.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/microsoft-power-bi-up-running-with-power-bi-desktop/',
      instructor: 'Maven Analytics',
      rating: 4.6,
      students: '250,000+',
    },
    {
      name: 'Power BI Basics',
      category: 'Business Intelligence',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn Power BI from scratch for data visualization and reporting. FREE course.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/power-bi',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '300K+',
    },
    {
      name: 'Tableau Complete Training',
      category: 'Data Visualization',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Learn Tableau from scratch and create stunning data visualizations and interactive dashboards.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/tableau10/',
      instructor: 'Kirill Eremenko',
      rating: 4.6,
      students: '330,000+',
    },
    {
      name: 'Google Data Analytics Professional Certificate',
      category: 'Data Analytics',
      duration: '40 hours',
      level: 'Beginner',
      description: 'Learn data cleaning, analysis, and visualization with spreadsheets, SQL, R, and Tableau.',
      platform: 'Coursera',
      url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
      instructor: 'Google',
      rating: 4.8,
      students: '2M+',
    },
    
    // FREE BBA - Business Administration courses from multiple platforms
    {
      name: 'Introduction to Marketing',
      category: 'Marketing',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Learn marketing fundamentals, branding, digital marketing strategies. FREE from Wharton.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/wharton-marketing',
      instructor: 'University of Pennsylvania',
      rating: 4.8,
      students: '750K+',
    },
    {
      name: 'Business Management Fundamentals',
      category: 'Business Management',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn business basics, management principles, leadership skills. FREE course.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/business-management',
      instructor: 'Great Learning',
      rating: 4.6,
      students: '300K+',
    },
    {
      name: 'Digital Marketing Complete Course',
      category: 'Marketing',
      duration: '25 hours',
      level: 'Beginner',
      description: 'Master digital marketing, SEO, social media, content marketing. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/digital-marketing',
      instructor: 'Great Learning',
      rating: 4.7,
      students: '500K+',
    },
    {
      name: 'Introduction to Operations Management',
      category: 'Operations',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn operations management, process improvement, supply chain basics. Completely FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/wharton-operations',
      instructor: 'University of Pennsylvania',
      rating: 4.7,
      students: '400K+',
    },
    {
      name: 'Human Resource Management Basics',
      category: 'Human Resources',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Learn HR fundamentals, recruitment, training, and employee relations. FREE.',
      platform: 'Shiksha Online (FREE)',
      url: 'https://www.shiksha.com/online-courses/hr-courses',
      instructor: 'Shiksha',
      rating: 4.5,
      students: '200K+',
    },
    {
      name: 'Digital Marketing Masterclass',
      category: 'Marketing',
      duration: '23 hours',
      level: 'Beginner',
      description: 'Learn SEO, social media marketing, email marketing, content strategy, and build a complete digital marketing campaign.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/learn-digital-marketing-course/',
      instructor: 'Phil Ebiner',
      rating: 4.5,
      students: '260,000+',
    },
    {
      name: 'Strategic Management & Business Strategy',
      category: 'Business Strategy',
      duration: '16 hours',
      level: 'Intermediate',
      description: 'Master strategic planning, competitive analysis, SWOT, Porter\'s Five Forces, and business models.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/strategic-management/',
      instructor: 'Chris Croft',
      rating: 4.5,
      students: '95,000+',
    },
    {
      name: 'Human Resources Management Course',
      category: 'Human Resources',
      duration: '18 hours',
      level: 'Beginner',
      description: 'Learn recruitment, training, performance management, employee relations, and HR best practices.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/human-resources-training/',
      instructor: 'Sorin Dumitrascu',
      rating: 4.4,
      students: '150,000+',
    },
    {
      name: 'Entrepreneurship Basics',
      category: 'Entrepreneurship',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn how to start a business, business planning, funding, and growth strategies. FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/entrepreneurship',
      instructor: 'University of Pennsylvania',
      rating: 4.6,
      students: '300K+',
    },
    {
      name: 'Supply Chain Management Fundamentals',
      category: 'Operations',
      duration: '15 hours',
      level: 'Intermediate',
      description: 'Master logistics, procurement, inventory management, and supply chain optimization.',
      platform: 'Udemy',
      url: 'https://www.udemy.com/course/supply-chain-management/',
      instructor: 'Start-Tech Academy',
      rating: 4.5,
      students: '110,000+',
    },
    
    // General skills with FREE options from multiple platforms
    {
      name: 'Introduction to Artificial Intelligence',
      category: 'AI',
      duration: '30 hours',
      level: 'Beginner',
      description: 'Learn AI basics, machine learning, neural networks from IBM. Completely FREE.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/introduction-to-ai',
      instructor: 'IBM',
      rating: 4.7,
      students: '500K+',
    },
    {
      name: 'Project Management Principles',
      category: 'Project Management',
      duration: '20 hours',
      level: 'Beginner',
      description: 'Learn project management basics, Agile, Scrum methodologies. FREE from Google.',
      platform: 'Coursera (FREE)',
      url: 'https://www.coursera.org/learn/project-management-foundations',
      instructor: 'Google',
      rating: 4.8,
      students: '1.2M+',
    },
    {
      name: 'Project Management Fundamentals',
      category: 'Project Management',
      duration: '15 hours',
      level: 'Beginner',
      description: 'Master project planning, execution, and delivery. FREE certification.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/project-management',
      instructor: 'Great Learning',
      rating: 4.6,
      students: '250K+',
    },
    {
      name: 'Communication Skills for Success',
      category: 'Soft Skills',
      duration: '10 hours',
      level: 'Beginner',
      description: 'Master public speaking, presentations, business communication. FREE course.',
      platform: 'YouTube (FREE)',
      url: 'https://www.youtube.com/watch?v=HAnw168huqA',
      instructor: 'TED',
      rating: 4.7,
      students: '800K+',
    },
    {
      name: 'Blockchain Basics',
      category: 'Blockchain',
      duration: '12 hours',
      level: 'Beginner',
      description: 'Learn blockchain technology, cryptocurrency, smart contracts. Completely FREE.',
      platform: 'Great Learning Academy (FREE)',
      url: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/blockchain',
      instructor: 'Great Learning',
      rating: 4.6,
      students: '180K+',
    },
  ];

  // Filter based on query and category
  const lowerQuery = query.toLowerCase();
  const lowerCategory = category.toLowerCase();
  
  return allCourses.filter(course => {
    const matchesQuery = !query || 
      course.name.toLowerCase().includes(lowerQuery) ||
      course.category.toLowerCase().includes(lowerQuery) ||
      course.description.toLowerCase().includes(lowerQuery);
    
    const matchesCategory = !category || 
      course.category.toLowerCase().includes(lowerCategory);
    
    return matchesQuery && matchesCategory;
  });
}

export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const body = await request.json();
    const { education, skills, interests } = body;

    // Determine category based on education
    let category = '';
    const eduLower = (education || '').toLowerCase();
    
    if (eduLower.includes('bca') || eduLower.includes('computer') || eduLower.includes('engineering')) {
      category = 'programming web development computer';
    } else if (eduLower.includes('bcom') || eduLower.includes('b.com') || eduLower.includes('commerce')) {
      category = 'accounting finance business taxation';
    } else if (eduLower.includes('bda') || eduLower.includes('data analytics') || eduLower.includes('business analytics')) {
      category = 'business analytics data visualization';
    } else if (eduLower.includes('bba') || eduLower.includes('b.b.a') || eduLower.includes('business administration')) {
      category = 'marketing hr strategy operations entrepreneurship';
    } else if (eduLower.includes('science')) {
      category = 'data science machine learning';
    }

    // Build search query from skills and interests
    const searchTerms = [...(skills || []), ...(interests || [])].join(' ');
    
    const courses = getCuratedCourses(searchTerms, category);

    return NextResponse.json({
      courses: courses.slice(0, 12), // Limit to 12 courses
      source: 'multiple',
    });

  } catch (error) {
    console.error('Course search error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}