import { db } from '@/db';
import { jobs } from '@/db/schema';

async function main() {
    const sampleJobs = [
        // Software Developer roles (20 listings)
        {
            title: 'Senior Full Stack Developer',
            company: 'Google',
            location: 'Bangalore',
            salary: 2800000,
            description: 'Join Google\'s engineering team to build next-generation web applications that serve millions of users worldwide.\n\nKey Responsibilities:\n• Design and develop scalable full-stack web applications using modern frameworks\n• Architect microservices-based solutions and RESTful APIs\n• Collaborate with cross-functional teams including product managers, designers, and other engineers\n• Mentor junior developers and conduct code reviews\n• Optimize application performance and ensure high availability\n• Implement automated testing and CI/CD pipelines\n\nRequired Qualifications:\n• 5+ years of professional experience in full-stack development\n• Strong proficiency in React, Node.js, TypeScript, and modern JavaScript\n• Experience with cloud technologies (GCP, AWS, or Azure)\n• Deep understanding of microservices architecture and distributed systems\n• Excellent problem-solving skills and attention to detail\n• Bachelor\'s degree in Computer Science or related field\n\nPreferred Skills:\n• Experience with GraphQL, Docker, and Kubernetes\n• Knowledge of system design and scalability patterns\n• Contributions to open-source projects\n\nBenefits:\n• Competitive salary with annual bonuses\n• Comprehensive health insurance for you and your family\n• Flexible work arrangements and remote work options\n• Learning and development budget\n• Stock options and retirement benefits\n• On-site gym, cafeteria, and recreational facilities',
            type: 'Full-time',
            postedDate: '2024-01-28',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Frontend Developer',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 1200000,
            description: 'Be part of Flipkart\'s frontend engineering team and create exceptional user experiences for India\'s largest e-commerce platform.\n\nAbout the Role:\nWe\'re looking for a passionate Frontend Developer who loves building beautiful, responsive, and performant web applications. You\'ll work on features used by millions of users daily and have the opportunity to make a significant impact.\n\nKey Responsibilities:\n• Develop and maintain responsive web applications using React and TypeScript\n• Implement pixel-perfect UI designs with modern CSS frameworks (Tailwind, styled-components)\n• Optimize web applications for maximum speed and scalability\n• Collaborate with backend developers to integrate RESTful APIs\n• Write clean, maintainable code with comprehensive unit tests\n• Participate in agile ceremonies and sprint planning\n• Debug and troubleshoot production issues\n\nRequired Skills:\n• 3-4 years of hands-on experience with React and modern JavaScript (ES6+)\n• Strong proficiency in HTML5, CSS3, and responsive design principles\n• Experience with state management libraries (Redux, Context API, Zustand)\n• Knowledge of build tools like Webpack, Vite, or Rollup\n• Understanding of web performance optimization techniques\n• Familiarity with Git version control and collaborative development\n\nNice to Have:\n• Experience with Next.js or other React frameworks\n• Knowledge of testing frameworks (Jest, React Testing Library)\n• Understanding of accessibility standards (WCAG)\n• Experience with Progressive Web Apps (PWAs)\n\nWhat We Offer:\n• Competitive compensation package\n• Health and wellness benefits\n• Flexible work hours and hybrid work model\n• Annual learning budget for courses and conferences\n• Employee stock options\n• Team outings and company events',
            type: 'Full-time',
            postedDate: '2024-01-27',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Backend Developer - Java',
            company: 'TCS',
            location: 'Pune',
            salary: 900000,
            description: 'Join TCS as a Backend Developer and work on enterprise-grade applications for global clients across various industries.\n\nPosition Overview:\nWe are seeking a talented Java Backend Developer to design, develop, and maintain robust server-side applications. You will be part of a dynamic team working on challenging projects that require strong technical expertise and problem-solving abilities.\n\nCore Responsibilities:\n• Design and develop RESTful APIs and microservices using Java and Spring Boot\n• Write efficient, reusable, and reliable code following best practices\n• Implement database schemas and optimize SQL queries for performance\n• Integrate third-party services and APIs\n• Participate in code reviews and maintain code quality standards\n• Debug and resolve production issues in a timely manner\n• Create and maintain technical documentation\n• Work closely with frontend developers and QA teams\n\nMust-Have Requirements:\n• 2-3 years of experience in Java backend development\n• Strong knowledge of Spring Framework (Spring Boot, Spring MVC, Spring Data)\n• Proficiency in developing RESTful web services\n• Experience with relational databases (MySQL, PostgreSQL) and ORM frameworks (Hibernate, JPA)\n• Understanding of microservices architecture and design patterns\n• Solid grasp of object-oriented programming and SOLID principles\n• Experience with Git and version control workflows\n\nAdditional Skills:\n• Knowledge of message queues (RabbitMQ, Kafka)\n• Experience with Docker and containerization\n• Familiarity with cloud platforms (AWS, Azure)\n• Understanding of CI/CD pipelines\n• Experience with NoSQL databases (MongoDB, Redis)\n\nEmployee Benefits:\n• Competitive salary and performance bonuses\n• Comprehensive medical insurance\n• Professional development opportunities\n• Work-life balance initiatives\n• Provident fund and gratuity\n• Transportation facilities',
            type: 'Full-time',
            postedDate: '2024-01-26',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Software Development Engineer',
            company: 'Amazon',
            location: 'Hyderabad',
            salary: 2200000,
            description: 'Amazon is looking for a talented Software Development Engineer to join our team building world-class distributed systems at massive scale.\n\nPosition Summary:\nAs an SDE at Amazon, you will be responsible for designing, developing, and deploying highly scalable services that power Amazon\'s customer-facing applications. You\'ll work with cutting-edge technologies and solve complex problems that impact millions of customers.\n\nKey Responsibilities:\n• Design and develop distributed systems using Java or Python\n• Build highly available and fault-tolerant services on AWS\n• Write clean, efficient, and well-documented code\n• Participate in design reviews and architecture discussions\n• Optimize system performance and reduce operational costs\n• Mentor junior engineers and contribute to team growth\n• Participate in on-call rotation for production support\n\nRequired Qualifications:\n• 4+ years of software development experience\n• Strong proficiency in Java, Python, or similar object-oriented languages\n• Deep understanding of data structures and algorithms\n• Experience with AWS services (EC2, S3, Lambda, DynamoDB)\n• Bachelor\'s degree in Computer Science or related field\n• Excellent problem-solving and analytical skills\n\nPreferred Qualifications:\n• Experience with distributed systems and microservices\n• Knowledge of NoSQL databases and caching strategies\n• Contributions to open-source projects\n• Master\'s degree in Computer Science\n\nWhat Amazon Offers:\n• Competitive total compensation package\n• RSUs (Restricted Stock Units)\n• Comprehensive health and dental coverage\n• Parental leave and family support\n• Career development and learning opportunities\n• Employee discount programs',
            type: 'Full-time',
            postedDate: '2024-01-25',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Junior Software Developer',
            company: 'Infosys',
            location: 'Bangalore',
            salary: 450000,
            description: 'Kickstart your career in technology with Infosys as a Junior Software Developer. This is an excellent opportunity for fresh graduates to learn and grow in a supportive environment.\n\nAbout the Program:\nJoin our comprehensive training program where you\'ll receive hands-on experience in full-stack development. You\'ll work on real client projects under the guidance of experienced mentors and develop skills that will accelerate your career.\n\nWhat You\'ll Do:\n• Participate in intensive training on Java, Angular, and SQL\n• Work on web application development projects\n• Write clean, maintainable code following best practices\n• Collaborate with team members in agile sprints\n• Learn about software development lifecycle and methodologies\n• Debug and troubleshoot application issues\n• Document code and technical specifications\n\nWe\'re Looking For:\n• Fresh graduates or 0-1 year of experience\n• Degree in Computer Science, IT, or related field (BE/B.Tech/MCA)\n• Strong programming fundamentals in any language\n• Basic understanding of databases and web technologies\n• Eagerness to learn new technologies\n• Good communication and teamwork skills\n• Problem-solving mindset\n\nWhat We Provide:\n• Structured training program (3-6 months)\n• Mentorship from senior developers\n• Exposure to various technologies and domains\n• Clear career progression path\n\nEmployee Benefits:\n• Competitive starting salary\n• Health insurance coverage\n• Professional certification support\n• Performance-based salary increments\n• Transportation and meal allowances\n• Work-life balance initiatives',
            type: 'Full-time',
            postedDate: '2024-01-24',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Full Stack Developer - MERN',
            company: 'Swiggy',
            location: 'Bangalore',
            salary: 1500000,
            description: 'Join Swiggy\'s engineering team to build innovative features for India\'s leading food delivery platform using the MERN stack.\n\nRole Overview:\nAs a Full Stack Developer at Swiggy, you\'ll own end-to-end feature development, from database design to frontend implementation. You\'ll work on high-impact projects that directly improve the experience for millions of users and restaurant partners.\n\nCore Responsibilities:\n• Build scalable web applications using MongoDB, Express.js, React, and Node.js\n• Design and implement RESTful APIs and microservices\n• Create responsive and intuitive user interfaces\n• Optimize application performance and database queries\n• Write unit and integration tests for robust code quality\n• Collaborate with product managers and designers\n• Participate in code reviews and technical discussions\n• Deploy and monitor applications in production\n\nRequired Experience:\n• 3-5 years of full-stack development experience\n• Strong expertise in JavaScript/TypeScript and the MERN stack\n• Proficiency in MongoDB database design and query optimization\n• Experience building and consuming RESTful APIs\n• Knowledge of modern JavaScript frameworks and libraries\n• Understanding of agile development practices\n• Strong debugging and problem-solving skills\n\nNice to Have:\n• Experience in food-tech or e-commerce domain\n• Knowledge of Redis, Elasticsearch, or message queues\n• Familiarity with Docker and Kubernetes\n• Experience with AWS or GCP\n• Understanding of payment gateway integrations\n\nPerks & Benefits:\n• Competitive salary package\n• Employee stock ownership plan (ESOP)\n• Health and wellness benefits\n• Flexible working hours\n• Free meals and snacks\n• Annual learning budget\n• Team outings and events',
            type: 'Full-time',
            postedDate: '2024-01-23',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Senior Backend Engineer',
            company: 'Razorpay',
            location: 'Bangalore',
            salary: 3200000,
            description: 'Razorpay is seeking an exceptional Senior Backend Engineer to design and build our next-generation payment processing systems.\n\nThe Opportunity:\nWork on critical payment infrastructure that processes billions of rupees in transactions daily. You\'ll architect high-availability systems that require 99.99% uptime and handle millions of requests per second during peak times.\n\nKey Responsibilities:\n• Design and develop scalable payment processing microservices\n• Build fault-tolerant distributed systems with strong consistency guarantees\n• Optimize database performance for high-throughput scenarios\n• Implement security best practices for financial transactions\n• Monitor system health and resolve production incidents\n• Lead technical design discussions and architecture reviews\n• Mentor team members and establish engineering best practices\n• Work with compliance teams to ensure regulatory adherence\n\nRequired Qualifications:\n• 6+ years of backend development experience\n• Expert-level knowledge of Python or Go\n• Deep understanding of distributed systems and microservices\n• Strong experience with PostgreSQL and Redis\n• Knowledge of payment systems, transaction processing, or fintech\n• Experience with high-scale, low-latency systems\n• Strong understanding of security and data protection\n• Excellent system design and problem-solving skills\n\nTechnical Skills:\n• Message queues (RabbitMQ, Kafka)\n• API design and versioning strategies\n• Database sharding and replication\n• Performance monitoring and optimization\n• CI/CD pipelines and DevOps practices\n\nWhat We Offer:\n• Industry-leading compensation\n• Substantial equity grants\n• Premium health insurance for family\n• Flexible work arrangements\n• Learning and conference budget\n• Latest hardware and tools\n• Vibrant office culture',
            type: 'Full-time',
            postedDate: '2024-01-22',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'React Developer',
            company: 'Zomato',
            location: 'Gurgaon',
            salary: 1100000,
            description: 'Join Zomato as a React Developer and help build India\'s most loved food delivery and restaurant discovery platform.\n\nAbout This Role:\nYou\'ll be responsible for creating seamless user experiences across web platforms, working on features that millions of users interact with daily. From restaurant listings to order tracking, your code will directly impact how people discover and enjoy food.\n\nKey Responsibilities:\n• Build responsive web applications using React and TypeScript\n• Implement modern UI/UX designs with attention to detail\n• Optimize application performance and loading times\n• Work with REST APIs and GraphQL for data integration\n• Write comprehensive unit and integration tests\n• Collaborate with designers and backend engineers\n• Participate in sprint planning and code reviews\n• Debug and resolve production issues quickly\n\nRequired Qualifications:\n• 2-4 years of React development experience\n• Strong proficiency in JavaScript ES6+ and TypeScript\n• Experience with state management (Redux, Context API, Recoil)\n• Knowledge of modern CSS and CSS-in-JS solutions\n• Understanding of responsive design and mobile-first approach\n• Familiarity with testing frameworks (Jest, React Testing Library)\n• Experience with Git and agile methodologies\n\nPreferred Skills:\n• Experience with Next.js or similar frameworks\n• Knowledge of performance optimization techniques\n• Understanding of SEO best practices\n• Experience with food-tech or consumer-facing apps\n• Familiarity with animation libraries (Framer Motion, React Spring)\n\nWhat We Offer:\n• Competitive salary and benefits\n• Health insurance for you and family\n• Flexible work hours and hybrid model\n• Free food credits on Zomato\n• Learning and development budget\n• Fun office culture with regular events',
            type: 'Full-time',
            postedDate: '2024-01-21',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Software Engineer - Python',
            company: 'Wipro',
            location: 'Hyderabad',
            salary: 850000,
            description: 'Wipro is looking for a Python Software Engineer to develop backend services and automation solutions for our global clients.\n\nPosition Overview:\nWork on diverse projects across industries including finance, healthcare, and retail. You\'ll develop scalable backend systems, APIs, and automation tools that solve real business problems.\n\nCore Responsibilities:\n• Develop backend services using Python and Django/Flask\n• Build and maintain RESTful APIs\n• Design and optimize database schemas\n• Write clean, tested, and documented code\n• Implement automation scripts and tools\n• Integrate third-party services and APIs\n• Participate in agile development processes\n• Troubleshoot and resolve technical issues\n\nRequired Skills:\n• 2-3 years of Python development experience\n• Strong knowledge of Django or Flask framework\n• Experience with SQL databases (PostgreSQL, MySQL)\n• Understanding of REST API design principles\n• Proficiency in Git version control\n• Knowledge of Linux/Unix environments\n• Good problem-solving and debugging skills\n\nAdditional Skills:\n• Experience with Docker containerization\n• Knowledge of Redis or other caching solutions\n• Familiarity with AWS or Azure cloud services\n• Understanding of CI/CD pipelines\n• Experience with async programming (asyncio, Celery)\n\nEmployee Benefits:\n• Competitive salary package\n• Health and life insurance\n• Professional training and certifications\n• Work-life balance programs\n• Transportation allowance\n• Provident fund and retirement benefits',
            type: 'Full-time',
            postedDate: '2024-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Lead Software Developer',
            company: 'Microsoft',
            location: 'Bangalore',
            salary: 4500000,
            description: 'Microsoft is seeking an exceptional Lead Software Developer to drive technical excellence and lead engineering teams building enterprise cloud solutions.\n\nThe Opportunity:\nLead a talented team of engineers working on Azure cloud services used by millions of businesses worldwide. You\'ll shape technical direction, mentor developers, and deliver high-impact solutions.\n\nLeadership Responsibilities:\n• Lead and mentor a team of 5-8 software engineers\n• Define technical architecture and make key design decisions\n• Drive engineering best practices and code quality standards\n• Conduct design reviews and provide technical guidance\n• Collaborate with product managers and stakeholders\n• Manage project timelines and deliverables\n• Foster a culture of innovation and continuous improvement\n• Participate in hiring and talent development\n\nTechnical Responsibilities:\n• Design and develop enterprise-scale applications using C# and .NET Core\n• Build cloud-native services on Microsoft Azure\n• Implement microservices and distributed systems\n• Optimize system performance and scalability\n• Ensure security and compliance requirements\n• Write technical documentation and specifications\n\nRequired Qualifications:\n• 8+ years of software development experience\n• 3+ years of technical leadership experience\n• Expert knowledge of C#, .NET Core, and Azure\n• Strong understanding of distributed systems architecture\n• Experience with agile methodologies (Scrum, Kanban)\n• Excellent communication and mentorship skills\n• Bachelor\'s or Master\'s degree in Computer Science\n\nPreferred Skills:\n• Experience with Kubernetes and containerization\n• Knowledge of DevOps practices and tools\n• Understanding of enterprise security patterns\n• Contributions to open-source projects\n• Experience with global-scale applications\n\nMicrosoft Benefits:\n• Industry-leading compensation\n• Generous stock awards and bonuses\n• Comprehensive health benefits\n• Parental leave and family support\n• Continuous learning opportunities\n• Flexible work arrangements\n• World-class facilities and perks',
            type: 'Full-time',
            postedDate: '2024-01-19',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Node.js Developer',
            company: 'PhonePe',
            location: 'Bangalore',
            salary: 1400000,
            description: 'PhonePe is hiring Node.js Developers to build robust backend services for India\'s leading digital payments platform.\n\nAbout the Role:\nWork on critical payment infrastructure serving 400+ million users. Build high-performance APIs and microservices that process millions of transactions daily with zero downtime.\n\nKey Responsibilities:\n• Develop scalable backend services using Node.js and TypeScript\n• Design and implement RESTful APIs and microservices\n• Build real-time payment processing systems\n• Optimize database queries and application performance\n• Implement security best practices for financial transactions\n• Write comprehensive unit and integration tests\n• Monitor and troubleshoot production systems\n• Collaborate with frontend and DevOps teams\n\nRequired Experience:\n• 3-4 years of Node.js backend development\n• Strong proficiency in JavaScript/TypeScript and Express.js\n• Experience with MongoDB and relational databases\n• Understanding of microservices architecture\n• Knowledge of message queues (RabbitMQ, Kafka)\n• Experience with Redis and caching strategies\n• Familiarity with Docker and Kubernetes\n\nDomain Knowledge:\n• Understanding of payment systems and UPI\n• Knowledge of API security (OAuth, JWT, encryption)\n• Experience with high-availability systems\n• Familiarity with PCI-DSS compliance\n\nTechnical Skills:\n• RESTful API design and versioning\n• Database design and optimization\n• Performance monitoring and profiling\n• Git workflow and CI/CD pipelines\n• AWS or GCP cloud services\n\nWhat PhonePe Offers:\n• Competitive compensation package\n• ESOPs (Employee Stock Options)\n• Premium health insurance\n• Flexible work policies\n• Learning and development budget\n• State-of-the-art office facilities\n• Regular team events and activities',
            type: 'Full-time',
            postedDate: '2024-01-18',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Junior Full Stack Developer',
            company: 'HCL',
            location: 'Noida',
            salary: 500000,
            description: 'Entry to mid-level position for developers with 1-2 years of experience. Work on web applications using React, Node.js, and MySQL. Good understanding of HTML, CSS, JavaScript, and basic database concepts required.',
            type: 'Full-time',
            postedDate: '2024-01-17',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Software Development Engineer II',
            company: 'Walmart Labs',
            location: 'Bangalore',
            salary: 2000000,
            description: 'Develop and optimize e-commerce platform features. Requires 4-6 years of experience with Java, Spring Boot, and distributed systems. Strong analytical skills and experience with high-traffic applications essential.',
            type: 'Full-time',
            postedDate: '2024-01-16',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Frontend Engineer - Angular',
            company: 'Tech Mahindra',
            location: 'Pune',
            salary: 950000,
            description: 'Build enterprise web applications using Angular and TypeScript. Need 2-3 years of experience with Angular framework, RxJS, and responsive design. Experience with NgRx state management is preferred.',
            type: 'Full-time',
            postedDate: '2024-01-15',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Senior Software Engineer - Go',
            company: 'Paytm',
            location: 'Noida',
            salary: 2500000,
            description: 'Design and implement high-performance backend services using Golang. Requires 5-7 years of experience with distributed systems, PostgreSQL, and message queues. Strong knowledge of fintech domain and microservices architecture needed.',
            type: 'Full-time',
            postedDate: '2024-01-14',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Full Stack JavaScript Developer',
            company: 'Cognizant',
            location: 'Chennai',
            salary: 1050000,
            description: 'Develop full stack applications using modern JavaScript stack. Must have 3-4 years of experience with React, Node.js, Express, and MongoDB. Good understanding of RESTful APIs and agile development practices required.',
            type: 'Full-time',
            postedDate: '2024-01-13',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Software Engineer - .NET',
            company: 'Accenture',
            location: 'Mumbai',
            salary: 800000,
            description: 'Build enterprise applications using .NET Core and C#. Need 2-3 years of experience with ASP.NET, SQL Server, and web services. Knowledge of Azure cloud services and DevOps practices is beneficial.',
            type: 'Full-time',
            postedDate: '2024-01-12',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Principal Software Engineer',
            company: 'Netflix',
            location: 'Mumbai',
            salary: 5200000,
            description: 'Lead technical architecture and development of streaming platform features. Requires 10+ years of experience with distributed systems, Java or Python, and cloud technologies. Strong mentorship skills and experience with large-scale systems essential.',
            type: 'Full-time',
            postedDate: '2024-01-11',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Backend Developer - PHP',
            company: 'Reliance Industries',
            location: 'Mumbai',
            salary: 750000,
            description: 'Develop and maintain backend systems using PHP and Laravel framework. Must have 2-3 years of experience with MySQL, REST APIs, and object-oriented programming. Experience with e-commerce platforms is a plus.',
            type: 'Full-time',
            postedDate: '2024-01-10',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Contract Full Stack Developer',
            company: 'IBM',
            location: 'Bangalore',
            salary: 1800000,
            description: '6-month contract position for experienced full stack developer. Work on enterprise applications using React, Java Spring Boot, and PostgreSQL. Requires 4+ years of experience with modern development practices and cloud deployment.',
            type: 'Contract',
            postedDate: '2024-01-09',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Data Science & ML roles (10 listings)
        {
            title: 'Senior Data Scientist',
            company: 'Google',
            location: 'Bangalore',
            salary: 3500000,
            description: 'Apply machine learning and statistical methods to solve complex business problems. Requires 5+ years of experience with Python, TensorFlow, and big data technologies. PhD or Masters in Data Science, Statistics, or related field preferred.',
            type: 'Full-time',
            postedDate: '2024-01-28',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Data Analyst',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 900000,
            description: 'Analyze large datasets to derive actionable insights for business decisions. Need 2-3 years of experience with SQL, Python, and visualization tools like Tableau or Power BI. Strong analytical and communication skills essential.',
            type: 'Full-time',
            postedDate: '2024-01-26',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Machine Learning Engineer',
            company: 'Amazon',
            location: 'Hyderabad',
            salary: 2800000,
            description: 'Design and implement ML models for recommendation and personalization systems. Requires 4-6 years of experience with Python, PyTorch, AWS SageMaker, and MLOps. Strong understanding of deep learning and production ML systems needed.',
            type: 'Full-time',
            postedDate: '2024-01-25',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'AI Research Engineer',
            company: 'Microsoft',
            location: 'Bangalore',
            salary: 4000000,
            description: 'Conduct cutting-edge research in natural language processing and computer vision. Must have 6+ years of experience with deep learning frameworks, research publications, and PhD in AI/ML. Experience with transformer models and LLMs highly desired.',
            type: 'Full-time',
            postedDate: '2024-01-24',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Junior Data Scientist',
            company: 'Swiggy',
            location: 'Bangalore',
            salary: 600000,
            description: 'Entry-level position for fresh graduates or candidates with 0-2 years of experience. Work on data analysis, model development, and A/B testing. Strong foundation in statistics, Python, and machine learning basics required.',
            type: 'Full-time',
            postedDate: '2024-01-22',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Data Scientist - NLP',
            company: 'Zomato',
            location: 'Gurgaon',
            salary: 2200000,
            description: 'Build NLP solutions for menu understanding and customer reviews. Need 4-5 years of experience with Python, spaCy, transformers, and deep learning. Experience with multilingual models and food-tech domain is beneficial.',
            type: 'Full-time',
            postedDate: '2024-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'ML Engineer - Computer Vision',
            company: 'TCS',
            location: 'Pune',
            salary: 1600000,
            description: 'Develop computer vision models for object detection and image classification. Requires 3-4 years of experience with OpenCV, TensorFlow, and CNN architectures. Experience with edge deployment and model optimization preferred.',
            type: 'Full-time',
            postedDate: '2024-01-18',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Senior Data Analyst',
            company: 'Paytm',
            location: 'Noida',
            salary: 1400000,
            description: 'Lead data analytics initiatives for fintech products. Must have 4-5 years of experience with SQL, Python, and BI tools. Strong business acumen and experience with financial data analysis essential.',
            type: 'Full-time',
            postedDate: '2024-01-16',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Data Engineer',
            company: 'Wipro',
            location: 'Bangalore',
            salary: 1200000,
            description: 'Build and maintain data pipelines and ETL processes. Need 3-4 years of experience with Spark, Hadoop, AWS, and SQL. Knowledge of data warehousing concepts and streaming technologies required.',
            type: 'Full-time',
            postedDate: '2024-01-14',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Part-time Data Analyst',
            company: 'Cognizant',
            location: 'Mumbai',
            salary: 400000,
            description: 'Part-time position (20 hours/week) for data analysis and reporting. Requires 2-3 years of experience with SQL, Excel, and Python. Flexible hours with remote work option available.',
            type: 'Part-time',
            postedDate: '2024-01-12',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Product Manager & Business Analyst roles (8 listings)
        {
            title: 'Senior Product Manager',
            company: 'Google',
            location: 'Bangalore',
            salary: 4200000,
            description: 'Lead product strategy and roadmap for cloud services. Requires 6+ years of product management experience with B2B SaaS products. Strong analytical skills, technical background, and experience with agile methodologies essential.',
            type: 'Full-time',
            postedDate: '2024-01-27',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Product Manager - Mobile',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 2500000,
            description: 'Drive mobile app product development and user experience. Need 4-5 years of experience managing mobile products, strong data-driven decision making, and collaboration with engineering teams. Experience in e-commerce is a plus.',
            type: 'Full-time',
            postedDate: '2024-01-25',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Technical Project Manager',
            company: 'Amazon',
            location: 'Hyderabad',
            salary: 2200000,
            description: 'Manage complex technical projects across multiple teams. Requires 5-7 years of project management experience with software development lifecycle. PMP certification and experience with AWS services preferred.',
            type: 'Full-time',
            postedDate: '2024-01-23',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Business Analyst',
            company: 'Accenture',
            location: 'Pune',
            salary: 950000,
            description: 'Analyze business requirements and translate them into technical specifications. Must have 3-4 years of experience with requirement gathering, documentation, and stakeholder management. Knowledge of SQL and Agile methodologies required.',
            type: 'Full-time',
            postedDate: '2024-01-21',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Associate Product Manager',
            company: 'Swiggy',
            location: 'Bangalore',
            salary: 1200000,
            description: 'Entry to mid-level position for product enthusiasts with 2-3 years of experience. Work on food delivery features, conduct user research, and analyze metrics. Strong analytical and communication skills essential.',
            type: 'Full-time',
            postedDate: '2024-01-19',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Senior Business Analyst',
            company: 'HDFC Bank',
            location: 'Mumbai',
            salary: 1600000,
            description: 'Lead business analysis for banking digital transformation projects. Requires 5-6 years of experience in financial services, strong analytical skills, and expertise in process improvement. Knowledge of banking regulations is important.',
            type: 'Full-time',
            postedDate: '2024-01-17',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Product Manager - Fintech',
            company: 'Razorpay',
            location: 'Bangalore',
            salary: 3000000,
            description: 'Define and execute product strategy for payment solutions. Need 5+ years of fintech product experience, understanding of payment systems, and strong technical acumen. Experience with B2B products preferred.',
            type: 'Full-time',
            postedDate: '2024-01-15',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Agile Project Manager',
            company: 'TCS',
            location: 'Chennai',
            salary: 1400000,
            description: 'Manage agile software development projects for enterprise clients. Requires 4-5 years of experience with Scrum, Kanban, and project management tools. CSM or PMP certification strongly preferred.',
            type: 'Full-time',
            postedDate: '2024-01-13',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // UI/UX Designer roles (5 listings)
        {
            title: 'Senior UI/UX Designer',
            company: 'Google',
            location: 'Bangalore',
            salary: 2800000,
            description: 'Create intuitive user experiences for cloud products. Requires 5+ years of UI/UX design experience, proficiency in Figma, Adobe XD, and strong portfolio. Experience with design systems and user research methodologies essential.',
            type: 'Full-time',
            postedDate: '2024-01-26',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'UI/UX Designer',
            company: 'Zomato',
            location: 'Gurgaon',
            salary: 1200000,
            description: 'Design user interfaces for food delivery app. Need 3-4 years of experience with user research, wireframing, and prototyping. Strong understanding of mobile-first design and interaction patterns required.',
            type: 'Full-time',
            postedDate: '2024-01-24',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Graphic Designer',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 700000,
            description: 'Create visual designs for marketing campaigns and product features. Must have 2-3 years of experience with Adobe Creative Suite, branding, and digital design. Portfolio showcasing creative work required.',
            type: 'Full-time',
            postedDate: '2024-01-22',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Product Designer',
            company: 'Microsoft',
            location: 'Hyderabad',
            salary: 2200000,
            description: 'Lead end-to-end design for enterprise software products. Requires 4-6 years of experience with design thinking, user research, and collaboration with product teams. Strong visual design and prototyping skills essential.',
            type: 'Full-time',
            postedDate: '2024-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Contract UX Designer',
            company: 'Paytm',
            location: 'Noida',
            salary: 1500000,
            description: '6-month contract for UX design of fintech products. Need 3+ years of experience with user research, information architecture, and usability testing. Experience with financial applications is highly desirable.',
            type: 'Contract',
            postedDate: '2024-01-18',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // DevOps & Cloud roles (7 listings)
        {
            title: 'Senior DevOps Engineer',
            company: 'Amazon',
            location: 'Bangalore',
            salary: 3200000,
            description: 'Build and maintain CI/CD pipelines and cloud infrastructure. Requires 5+ years of experience with AWS, Kubernetes, Docker, and Infrastructure as Code. Strong automation skills and experience with monitoring tools essential.',
            type: 'Full-time',
            postedDate: '2024-01-28',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Cloud Architect',
            company: 'Microsoft',
            location: 'Bangalore',
            salary: 4500000,
            description: 'Design cloud architecture for enterprise applications on Azure. Need 7+ years of experience with cloud platforms, microservices, and security best practices. Azure certifications and strong communication skills required.',
            type: 'Full-time',
            postedDate: '2024-01-26',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'DevOps Engineer',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 1600000,
            description: 'Implement and maintain DevOps practices for e-commerce platform. Must have 3-4 years of experience with Jenkins, GitLab CI, AWS, and scripting languages. Knowledge of containerization and orchestration tools required.',
            type: 'Full-time',
            postedDate: '2024-01-24',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Site Reliability Engineer',
            company: 'Google',
            location: 'Bangalore',
            salary: 3800000,
            description: 'Ensure reliability and scalability of distributed systems. Requires 6+ years of experience with SRE practices, monitoring tools, and incident management. Strong programming skills in Python or Go essential.',
            type: 'Full-time',
            postedDate: '2024-01-22',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Cloud Engineer - AWS',
            company: 'Wipro',
            location: 'Pune',
            salary: 1300000,
            description: 'Deploy and manage applications on AWS cloud infrastructure. Need 3-4 years of experience with EC2, S3, Lambda, and CloudFormation. AWS certification and experience with cost optimization preferred.',
            type: 'Full-time',
            postedDate: '2024-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'DevOps Lead',
            company: 'Cognizant',
            location: 'Chennai',
            salary: 2600000,
            description: 'Lead DevOps transformation initiatives for enterprise clients. Requires 6-8 years of experience with CI/CD, cloud platforms, and team leadership. Strong understanding of agile practices and automation frameworks needed.',
            type: 'Full-time',
            postedDate: '2024-01-18',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Junior DevOps Engineer',
            company: 'HCL',
            location: 'Noida',
            salary: 550000,
            description: 'Entry-level position for DevOps enthusiasts with 1-2 years of experience. Work on automation scripts, CI/CD pipelines, and cloud deployments. Good understanding of Linux, Docker, and basic scripting required.',
            type: 'Full-time',
            postedDate: '2024-01-16',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // QA Engineer roles (4 listings)
        {
            title: 'Senior QA Engineer',
            company: 'Amazon',
            location: 'Hyderabad',
            salary: 1800000,
            description: 'Lead quality assurance for e-commerce platform features. Requires 5+ years of testing experience with automation frameworks like Selenium, API testing, and performance testing. Strong analytical and problem-solving skills essential.',
            type: 'Full-time',
            postedDate: '2024-01-25',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Test Automation Engineer',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 1200000,
            description: 'Build and maintain automated test suites for web and mobile applications. Need 3-4 years of experience with Selenium, Appium, and CI/CD integration. Programming skills in Java or Python required.',
            type: 'Full-time',
            postedDate: '2024-01-23',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'QA Analyst',
            company: 'TCS',
            location: 'Pune',
            salary: 650000,
            description: 'Perform manual and automated testing for enterprise applications. Must have 2-3 years of testing experience, good understanding of SDLC, and knowledge of test management tools. ISTQB certification is a plus.',
            type: 'Full-time',
            postedDate: '2024-01-21',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Part-time QA Tester',
            company: 'Infosys',
            location: 'Bangalore',
            salary: 350000,
            description: 'Part-time position (20 hours/week) for manual testing. Requires 1-2 years of testing experience with web applications. Flexible hours with option to work remotely.',
            type: 'Part-time',
            postedDate: '2024-01-19',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Marketing roles (4 listings)
        {
            title: 'Marketing Manager',
            company: 'Flipkart',
            location: 'Bangalore',
            salary: 1800000,
            description: 'Lead digital marketing campaigns and brand strategy. Requires 5+ years of marketing experience with e-commerce, strong analytical skills, and expertise in performance marketing. Experience with SEO, SEM, and social media essential.',
            type: 'Full-time',
            postedDate: '2024-01-27',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Digital Marketing Specialist',
            company: 'Zomato',
            location: 'Gurgaon',
            salary: 900000,
            description: 'Execute digital marketing strategies across multiple channels. Need 3-4 years of experience with Google Ads, Facebook Ads, and marketing analytics. Strong understanding of customer acquisition and retention required.',
            type: 'Full-time',
            postedDate: '2024-01-24',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Growth Marketing Manager',
            company: 'Swiggy',
            location: 'Bangalore',
            salary: 2200000,
            description: 'Drive user growth and engagement through data-driven marketing. Requires 4-6 years of growth marketing experience, strong analytical skills, and experience with A/B testing. Knowledge of mobile app marketing is important.',
            type: 'Full-time',
            postedDate: '2024-01-22',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Contract Marketing Analyst',
            company: 'Paytm',
            location: 'Noida',
            salary: 800000,
            description: '6-month contract for marketing data analysis and reporting. Need 2-3 years of experience with marketing analytics tools, SQL, and Excel. Strong presentation and communication skills required.',
            type: 'Contract',
            postedDate: '2024-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // HR, Sales, Finance roles (4 listings)
        {
            title: 'HR Manager',
            company: 'Deloitte',
            location: 'Mumbai',
            salary: 1500000,
            description: 'Manage recruitment, employee relations, and HR operations. Requires 5+ years of HR experience in consulting or tech companies. Strong leadership, communication, and knowledge of labor laws essential.',
            type: 'Full-time',
            postedDate: '2024-01-26',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Sales Executive - Enterprise',
            company: 'Cisco',
            location: 'Bangalore',
            salary: 1200000,
            description: 'Drive enterprise sales for networking solutions. Need 3-5 years of B2B sales experience, strong negotiation skills, and understanding of networking technologies. Proven track record of meeting sales targets required.',
            type: 'Full-time',
            postedDate: '2024-01-23',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Financial Analyst',
            company: 'ICICI Bank',
            location: 'Mumbai',
            salary: 1000000,
            description: 'Perform financial analysis and modeling for banking products. Must have 3-4 years of experience with financial reporting, budgeting, and Excel. CA or MBA in Finance preferred. Strong analytical and problem-solving skills essential.',
            type: 'Full-time',
            postedDate: '2024-01-21',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Part-time HR Recruiter',
            company: 'EY',
            location: 'Bangalore',
            salary: 450000,
            description: 'Part-time position (25 hours/week) for technical recruitment. Requires 2-3 years of IT recruitment experience and strong sourcing skills. Flexible work arrangements available.',
            type: 'Part-time',
            postedDate: '2024-01-19',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(jobs).values(sampleJobs);
    
    console.log('✅ Jobs seeder completed successfully - Added 59 realistic job listings');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});